version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend/vite-project
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
